# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[9, 8, 0, 6, 4, 2, 4, 1, 5, 8, 2, 1],
       [3, 4, 3, 6, 0, 4, 7, 3, 5, 0, 2, 3],
       [2, 4, 9, 9, 2, 8, 5, 0, 7, 4, 6, 8],
       [7, 4, 1, 3, 2, 4, 7, 8, 4, 3, 1, 6],
       [2, 1, 3, 1, 6, 2, 4, 9, 5, 7, 3, 6],
       [7, 3, 1, 4, 8, 9, 5, 4, 6, 6, 6, 2],
       [5, 5, 2, 3, 6, 5, 0, 2, 6, 8, 9, 6],
       [7, 3, 2, 8, 8, 1, 2, 4, 0, 8, 1, 0],
       [7, 8, 8, 9, 6, 0, 2, 2, 7, 5, 8, 9],
       [1, 9, 9, 0, 3, 8, 5, 2, 5, 9, 9, 6],
       [1, 1, 7, 6, 6, 4, 4, 6, 4, 8, 5, 1],
       [2, 2, 6, 0, 8, 1, 0, 3, 5, 2, 2, 9]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [13]:
dst = np.zeros((h,w),np.uint)

In [14]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [15]:
img

array([[9, 8, 0, 6, 4, 2, 4, 1, 5, 8, 2, 1],
       [3, 4, 3, 6, 0, 4, 7, 3, 5, 0, 2, 3],
       [2, 4, 9, 9, 2, 8, 5, 0, 7, 4, 6, 8],
       [7, 4, 1, 3, 2, 4, 7, 8, 4, 3, 1, 6],
       [2, 1, 3, 1, 6, 2, 4, 9, 5, 7, 3, 6],
       [7, 3, 1, 4, 8, 9, 5, 4, 6, 6, 6, 2],
       [5, 5, 2, 3, 6, 5, 0, 2, 6, 8, 9, 6],
       [7, 3, 2, 8, 8, 1, 2, 4, 0, 8, 1, 0],
       [7, 8, 8, 9, 6, 0, 2, 2, 7, 5, 8, 9],
       [1, 9, 9, 0, 3, 8, 5, 2, 5, 9, 9, 6],
       [1, 1, 7, 6, 6, 4, 4, 6, 4, 8, 5, 1],
       [2, 2, 6, 0, 8, 1, 0, 3, 5, 2, 2, 9]])

In [16]:
dst

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 2, 2, 2, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 2, 2, 2, 0],
       [0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 2, 1, 1, 0, 0, 1, 2, 2, 0],
       [0, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 0],
       [0, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint32)

In [17]:
img = cv2.imread('lena.png', 0)

In [18]:
h,w=img.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [40]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [41]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [42]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
kernel = np.ones((5,5),np.float32)/25
#dst = cv2.filter2D(img,-1,kernel)
blur = cv2.blur(img,(5,5),0)
median = cv2.medianBlur(img,5)
plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(dst),plt.title('Averaging')
plt.xticks([]), plt.yticks([])
plt.show()


error: OpenCV(4.13.0) D:/a/opencv-python/opencv-python/opencv/modules/imgproc/src/median_blur.simd.hpp:887: error: (-210:Unsupported format or combination of formats)  in function 'cv::opt_AVX2::medianBlur'
